/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CatalogCard: typeof import('./../src/components/catalog/catalog-card.vue')['default']
    CatalogsActions: typeof import('./../src/components/catalogs-actions.vue')['default']
    LayoutActionsButton: typeof import('./../src/components/layout/layout-actions-button.vue')['default']
    LayoutNavigationRight: typeof import('./../src/components/layout/layout-navigation-right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
